services:
  app:
    build: .
    container_name: questly-typescript-app
    volumes:
      - .:/home/node/questly
  postgres:
    image: postgres:18-bookworm
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questly
